# Generated by Django 5.1.2 on 2024-11-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hair_name', models.CharField(max_length=100)),
                ('hair_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pant_name', models.CharField(max_length=100)),
                ('pant_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shirt_name', models.CharField(max_length=100)),
                ('shirt_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shoes_name', models.CharField(max_length=100)),
                ('shoes_type', models.CharField(max_length=50)),
            ],
        ),
    ]
